/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InputType } from "./types/input.types";
export { InputType } from "./types/input.types";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WcContainer {
    }
    interface WcInput {
        "disabled": boolean;
        "label": string;
        "type": InputType;
    }
    interface WcSelect {
        "defaultValue": string;
        "options": string[];
    }
}
export interface WcSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWcSelectElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWcContainerElement extends Components.WcContainer, HTMLStencilElement {
    }
    var HTMLWcContainerElement: {
        prototype: HTMLWcContainerElement;
        new (): HTMLWcContainerElement;
    };
    interface HTMLWcInputElement extends Components.WcInput, HTMLStencilElement {
    }
    var HTMLWcInputElement: {
        prototype: HTMLWcInputElement;
        new (): HTMLWcInputElement;
    };
    interface HTMLWcSelectElement extends Components.WcSelect, HTMLStencilElement {
    }
    var HTMLWcSelectElement: {
        prototype: HTMLWcSelectElement;
        new (): HTMLWcSelectElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "wc-container": HTMLWcContainerElement;
        "wc-input": HTMLWcInputElement;
        "wc-select": HTMLWcSelectElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WcContainer {
    }
    interface WcInput {
        "disabled"?: boolean;
        "label"?: string;
        "type"?: InputType;
    }
    interface WcSelect {
        "defaultValue"?: string;
        "onMySelectChange"?: (event: WcSelectCustomEvent<string>) => void;
        "options"?: string[];
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "wc-container": WcContainer;
        "wc-input": WcInput;
        "wc-select": WcSelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "wc-container": LocalJSX.WcContainer & JSXBase.HTMLAttributes<HTMLWcContainerElement>;
            "wc-input": LocalJSX.WcInput & JSXBase.HTMLAttributes<HTMLWcInputElement>;
            "wc-select": LocalJSX.WcSelect & JSXBase.HTMLAttributes<HTMLWcSelectElement>;
        }
    }
}
